In [16]:
import numpy as np
from sklearn.neural_network import MLPClassifier

x_train=np.array([[0,0],[0,1]])
y_train=np.array([0,1])


x_test=np.array([[2.,2.],[-1.,-2.]])


MLP_clf = MLPClassifier(hidden_layer_sizes=(4), activation='logistic', solver='lbfgs', alpha=0.0001, learning_rate='adaptive')
MLP_clf.fit(x_train, y_train)
y_pred = MLP_clf.predict(x_test)
print(y_pred)

print ("les coefficients sont: "+str( MLP_clf.coefs_))
print ("les biais des couche cachees  et la sortie sont :" +str(MLP_clf.intercepts_))

[1 0]
les coefficients sont: [array([[ 1.43489068e-02,  5.07534374e-02, -9.34337985e-02,
        -2.59903078e-03],
       [-4.64025661e+00, -4.62478434e+00,  1.02293911e+00,
        -3.73727076e+00]]), array([[-6.35781503],
       [-6.29120183],
       [ 1.43169671],
       [-5.15952764]])]
les biais des couche cachees  et la sortie sont :[array([2.39485147, 2.35046331, 0.27027977, 1.86539351]), array([7.98475113])]


In [14]:
import numpy as np
from sklearn.neural_network import MLPClassifier

x_train=np.array([[0,0],[1,1]])
y_train=np.array([[0, 1],[1, 1]])
x_test=np.array([[2.,2.],[-1.,-2.]])
MLP_clf = MLPClassifier(hidden_layer_sizes=(4), activation='logistic', solver='lbfgs', alpha=0.0001, learning_rate='adaptive')
MLP_clf.fit(x_train, y_train)
y_pred = MLP_clf.predict(x_test)
print("les prediction sont :" +str(y_pred))
print ("les coefficients sont: "+str( MLP_clf.coefs_))
print ("les biais des couche cachees  et la sortie sont :" +str(MLP_clf.intercepts_))

les prediction sont :[[1 1]
 [0 1]]
les coefficients sont: [array([[ 1.404451  , -2.77703753,  2.4980617 , -2.73815629],
       [ 1.41587339, -2.77495584,  2.49761427, -2.73895053]]), array([[ 2.53183829,  0.15595431],
       [-5.99050145,  0.18102598],
       [ 3.53072429,  0.18911753],
       [-6.05546327,  0.11455512]])]
les biais des couche cachees  et la sortie sont :[array([-1.3454215 ,  3.04150961, -3.23784567,  2.99942232]), array([ 3.30372972, 10.16717894])]


In [48]:
from sklearn.model_selection import GridSearchCV

X_train2 = np.array([[0,0],[1,1]])
y_train2 = np.array([[0,1],[1,1]])
X_test2 = np.array([[2.,2.],[-1.,-2.]])
param_grid = {
    'hidden_layer_sizes': [2, 3, 4, 5, 6, 7, 8],

    }
 
mlp_clf = GridSearchCV(MLPClassifier(activation = 'logistic', solver = 'lbfgs', learning_rate = 'adaptive', max_iter = 100), param_grid, cv=2, n_jobs=4, verbose=1)
mlp_clf.fit(X_train2, y_train2)
y_predict = mlp_clf.predict(X_test2)
print("Les classes prédites pour les données de test {} sont: {} respectivement.".format(X_test, y_predict))
print("La meilleure configuration est: ", mlp_clf.best_params_)



Fitting 2 folds for each of 7 candidates, totalling 14 fits
Les classes prédites pour les données de test [[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [6.  2.9 4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.3 0.4]
 [5.6 2.8 4.9 2. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [4.6 3.6 1.  0.2]
 [5.1 3.8 1.9 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]
 [6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.  2.7 5.1 1.6]
 [5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  14 out of  14 | elapsed:    0.0s finished


In [58]:
import numpy as np
import time
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

iris = datasets.load_iris()

X= iris.data
y= iris.target
start_time = time.time()



def Hiddenlayersizes3(x1,y1,z1):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7,random_state=0)
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    MLP_clf = MLPClassifier(hidden_layer_sizes=(x1,y1,z1), activation='logistic', solver='lbfgs', learning_rate='adaptive')
    MLP_clf.fit(X_train, y_train)
    y_pred = MLP_clf.predict(X_test)
    score = MLP_clf.score(X_test, y_test)
    end_time = time.time()
    print("pour les 3 couche de taille : " +str(x1)+"-->"+str(y1)+"-->"+str(z1))
    print('temps ecoule = '+str(end_time - start_time))
    return print("le score est :"+str(score)) 
def Hiddenlayersizes2(x1,y1):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7,random_state=0)
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    MLP_clf = MLPClassifier(hidden_layer_sizes=(x1,y1), activation='logistic', solver='lbfgs', learning_rate='adaptive')
    MLP_clf.fit(X_train, y_train)
    y_pred = MLP_clf.predict(X_test)
    score = MLP_clf.score(X_test, y_test)
    end_time = time.time()
    print("pour les 2 couche de taille : " +str(x1)+"-->"+str(y1))
    print('temps ecoule = '+str(end_time - start_time))
    return print("le score est :"+str(score)) 
def Hiddenlayersizes4(x1,y1,z1,c1):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7,random_state=0)
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    MLP_clf = MLPClassifier(hidden_layer_sizes=(x1,y1,z1,c1), activation='logistic', solver='lbfgs', learning_rate='adaptive')
    MLP_clf.fit(X_train, y_train)
    y_pred = MLP_clf.predict(X_test)
    score = MLP_clf.score(X_test, y_test)
    end_time = time.time()
    print("pour les 4 couche de taille : " +str(x1)+"-->"+str(y1)+"-->"+str(z1)+"-->"+str(c1))
    print('temps ecoule = '+str(end_time - start_time))
    print(MLP_clf.n_iter_)
    return print("le score est :"+str(score)) 
# pour differentes taille des 2 couche de neuron 
Hiddenlayersizes2(1,15)
Hiddenlayersizes2(10,100)
Hiddenlayersizes2(200,300)

# pour differentes taille des 3 couche de neuron 
Hiddenlayersizes3(1,15,30)
Hiddenlayersizes3(10,100,200)
Hiddenlayersizes3(100,150,300)

# pour differentes taille des 4 couche de neuron 
Hiddenlayersizes4(1,15,30,90)
Hiddenlayersizes4(10,100,200,300)



C:\Users\utilisateur\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


pour les 2 couche de taille : 1-->15
temps ecoule = 0.12578940391540527
le score est :0.9619047619047619
pour les 2 couche de taille : 10-->100
temps ecoule = 0.20779061317443848
le score est :0.9523809523809523
pour les 2 couche de taille : 200-->300
temps ecoule = 1.0955638885498047
le score est :0.9619047619047619
pour les 3 couche de taille : 1-->15-->30
temps ecoule = 1.3302545547485352
le score est :0.9619047619047619
pour les 3 couche de taille : 10-->100-->200
temps ecoule = 1.8461182117462158
le score est :0.9523809523809523
pour les 3 couche de taille : 100-->150-->300
temps ecoule = 2.8674685955047607
le score est :0.9619047619047619


C:\Users\utilisateur\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


pour les 4 couche de taille : 1-->15-->30-->90
temps ecoule = 3.2577831745147705
200
le score est :0.9619047619047619
pour les 4 couche de taille : 10-->100-->200-->300
temps ecoule = 4.508488655090332
65
le score est :0.9619047619047619


In [53]:
from sklearn import svm
clsvm = svm.SVC(kernel='poly')
clsvm.fit(X_train, y_train)
y_pred = clsvm.predict(X_test)
score = clsvm.score(X_test, y_test)
print ("le score avec un classifieur a noyau de type SVM ="+str(score))


le score avec un classifieur a noyau de type SVM =0.9428571428571428


In [57]:
from statistics import mean, stdev
for i in range(len(X)):
    print("la valeur moyenne de l'attribut {} est: {}".format(i+1,mean(X[i])))
    print("l'écart-type de l'attribut {} est: {}".format(i+1,stdev(X[i])))

la valeur moyenne de l'attribut 1 est: 2.55
l'écart-type de l'attribut 1 est: 2.1794494717703365
la valeur moyenne de l'attribut 2 est: 2.375
l'écart-type de l'attribut 2 est: 2.036950334855189
la valeur moyenne de l'attribut 3 est: 2.35
l'écart-type de l'attribut 3 est: 1.997498435543818
la valeur moyenne de l'attribut 4 est: 2.35
l'écart-type de l'attribut 4 est: 1.9122412679017953
la valeur moyenne de l'attribut 5 est: 2.55
l'écart-type de l'attribut 5 est: 2.1563858652847823
la valeur moyenne de l'attribut 6 est: 2.85
l'écart-type de l'attribut 6 est: 2.230844384233617
la valeur moyenne de l'attribut 7 est: 2.425
l'écart-type de l'attribut 7 est: 1.9362764954072718
la valeur moyenne de l'attribut 8 est: 2.525
l'écart-type de l'attribut 8 est: 2.109304782781916
la valeur moyenne de l'attribut 9 est: 2.225
l'écart-type de l'attribut 9 est: 1.8227726133558184
la valeur moyenne de l'attribut 10 est: 2.4
l'écart-type de l'attribut 10 est: 2.06881608655772
la valeur moyenne de l'attribut

In [62]:
n=1000
tab = ("lbfgs", "sgd", "adam")
for i in tab:
    print('--------------------',i,'--------------------')
    start_time = time.time()
    clf1 = MLPClassifier(solver=i,hidden_layer_sizes=(200),max_iter=n,random_state=0)
    clf1.fit(X_train,y_train)
    end_time = time.time()
    print(clf1.score(X_test,y_test))
    print('temps ecoulé pour une couche cachée = '+str(end_time - start_time))
    print('n_iter',clf1.n_iter_)
    start_time = time.time()
    clf2 = MLPClassifier(solver =i,hidden_layer_sizes=(100,200),max_iter=n,random_state=0)
    clf2.fit(X_train,y_train)
    end_time = time.time()
    print(clf2.score(X_test,y_test))
    print('temps ecoulé pour 2 couche cachée = '+str(end_time - start_time))
    print('n_iter',clf2.n_iter_)
    start_time = time.time()
    clf3 = MLPClassifier(solver =i,hidden_layer_sizes=(100,200,300),max_iter=n,random_state=0)
    clf3.fit(X_train,y_train)
    end_time = time.time()
    print(clf3.score(X_test,y_test))
    print('temps ecoulé 3 couche cachée = '+str(end_time - start_time))
    print('n_iter',clf3.n_iter_)
    start_time = time.time()
    clf4 = MLPClassifier(solver =i,hidden_layer_sizes=(100,150,250,300),max_iter=n,random_state=0)
    clf4.fit(X_train,y_train)
    end_time = time.time()
    print(clf4.score(X_test,y_test))
    print('temps ecoulé 4 couche cachée = '+str(end_time - start_time))
    print('n_iter',clf4.n_iter_)
    start_time = time.time()
    clf5= MLPClassifier(solver =i,hidden_layer_sizes=(50,100,150,200,250,300),max_iter=n,random_state=0)
    clf5.fit(X_train,y_train)
    end_time = time.time()
    print(clf5.score(X_test,y_test))
    print('temps ecoulé 5 couche cachée = '+str(end_time - start_time))
    print('n_iter',clf5.n_iter_)
    print('_________________________________________________________________')

-------------------- lbfgs --------------------
0.9619047619047619
temps ecoulé pour une couche cachée = 0.03703498840332031
n_iter 20
0.9619047619047619
temps ecoulé pour 2 couche cachée = 0.1288442611694336
n_iter 21
0.9619047619047619
temps ecoulé 3 couche cachée = 0.5603196620941162
n_iter 25
0.9619047619047619
temps ecoulé 4 couche cachée = 0.9386575222015381
n_iter 26
0.9523809523809523
temps ecoulé 5 couche cachée = 4.265818357467651
n_iter 91
_________________________________________________________________
-------------------- sgd --------------------
0.8476190476190476
temps ecoulé pour une couche cachée = 0.9529769420623779
n_iter 899


C:\Users\utilisateur\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


0.8952380952380953
temps ecoulé pour 2 couche cachée = 1.7930026054382324
n_iter 1000
0.9333333333333333
temps ecoulé 3 couche cachée = 3.788252592086792
n_iter 979
0.9523809523809523
temps ecoulé 4 couche cachée = 4.6702985763549805
n_iter 890
0.9523809523809523
temps ecoulé 5 couche cachée = 5.430448055267334
n_iter 758
_________________________________________________________________
-------------------- adam --------------------
0.9619047619047619
temps ecoulé pour une couche cachée = 0.5190973281860352
n_iter 455
0.9428571428571428
temps ecoulé pour 2 couche cachée = 0.44471025466918945
n_iter 229
0.9428571428571428
temps ecoulé 3 couche cachée = 0.45997023582458496
n_iter 108
0.9428571428571428
temps ecoulé 4 couche cachée = 0.4910881519317627
n_iter 72
0.9428571428571428
temps ecoulé 5 couche cachée = 0.4994850158691406
n_iter 53
_________________________________________________________________


In [63]:
param_grid = {
    'alpha': [0.0001, 0.001, 0.1, 1]
    }
 
mlp_clf = GridSearchCV(MLPClassifier(hidden_layer_sizes = (2),activation = 'logistic', solver = 'lbfgs', learning_rate = 'adaptive', max_iter = 100), param_grid, cv=2, n_jobs=4, verbose=1)
mlp_clf.fit(X_train, y_train)
print("Le score est: ", mlp_clf.score(X_test, y_test))
print("La meilleure valeur pour alpha = {}".format(mlp_clf.best_estimator_.alpha))

Fitting 2 folds for each of 4 candidates, totalling 8 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.


Le score est:  0.9619047619047619
La meilleure valeur pour alpha = 0.001


[Parallel(n_jobs=4)]: Done   8 out of   8 | elapsed:    2.6s finished


In [1]:
import matplotlib.pyplot as plt
import time
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import fetch_openml
mnist = fetch_openml("mnist_784")

X, y = mnist.data / 255., mnist.target
X_train, X_test = X[:60000], X[60000:]
y_train, y_test = y[:60000], y[60000:]


start_time = time.time()

mlp = MLPClassifier(hidden_layer_sizes=(50,), max_iter=10, alpha=1e-4,
                    solver='sgd', verbose=10, tol=1e-4, random_state=1,
                    learning_rate_init=.1)

mlp.fit(X_train, y_train)
end_time = time.time()
print("le score d'entrainement est : %f" % mlp.score(X_train, y_train))
print("le score de test est : %f" % mlp.score(X_test, y_test))
print('temps ecoulé = '+str(end_time - start_time))

Iteration 1, loss = 0.32009978
Iteration 2, loss = 0.15347534
Iteration 3, loss = 0.11544755
Iteration 4, loss = 0.09279764
Iteration 5, loss = 0.07889367
Iteration 6, loss = 0.07170497
Iteration 7, loss = 0.06282111
Iteration 8, loss = 0.05530788
Iteration 9, loss = 0.04960484
Iteration 10, loss = 0.04645355


C:\Users\utilisateur\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


le score d'entrainement est : 0.986800
le score de test est : 0.970000
temps ecoulé = 65.73171329498291


In [ ]:
from sklearn.model_selection import GridSearchCV

#Appliquons un GridSearchCV pour trouver la meilleure configuration possible
param_grid = {
    'hidden_layer_sizes': [2, 30, 40, 50],
    'activation':['logistic','relu'],
    'solver':['lbfgs', 'sgd', 'adam'],
    'learning_rate':['adaptive'],
    'alpha': [0.0001, 0.001,0.01]
    }
 
mlp_clf = GridSearchCV(MLPClassifier(), param_grid, cv=3, n_jobs=4, verbose=1)
mlp_clf.fit(X_train_flat, y_train)
y_predict = mlp_clf.predict(X_test_flat)
print("Meilleur score : " + str(svm_clf.best_estimator_.score(X_test_flat, y_test)))
print("La meilleure configuration est: " + str(svm_clf.best_params_))

Fitting 3 folds for each of 48 candidates, totalling 144 fits


[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.


In [7]:
import numpy as np
import time
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron 
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()

X= iris.data
y= iris.target
print(X)
iris.head()


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

AttributeError: head